// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxZL_0UYyT9auJJ0JJX8NfEEo1mA5UOgI',
    appId: '1:877892625400:web:279cc7438f623434e2ac0d',
    messagingSenderId: '877892625400',
    projectId: 'yoga-app-831a3',
    authDomain: 'yoga-app-831a3.firebaseapp.com',
    storageBucket: 'yoga-app-831a3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlRKHw6DYfWSE2GVodg6exzLLRk2Ofl18',
    appId: '1:877892625400:android:31b145c2bf3f37b8e2ac0d',
    messagingSenderId: '877892625400',
    projectId: 'yoga-app-831a3',
    storageBucket: 'yoga-app-831a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzXkDk5mh4MXSlduADYjat_FetU0KeKdk',
    appId: '1:877892625400:ios:42e2e5951952890de2ac0d',
    messagingSenderId: '877892625400',
    projectId: 'yoga-app-831a3',
    storageBucket: 'yoga-app-831a3.appspot.com',
    iosClientId: '877892625400-gdne2nma7gphtctflnopg1thf0oujrud.apps.googleusercontent.com',
    iosBundleId: 'com.example.yogaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzXkDk5mh4MXSlduADYjat_FetU0KeKdk',
    appId: '1:877892625400:ios:42e2e5951952890de2ac0d',
    messagingSenderId: '877892625400',
    projectId: 'yoga-app-831a3',
    storageBucket: 'yoga-app-831a3.appspot.com',
    iosClientId: '877892625400-gdne2nma7gphtctflnopg1thf0oujrud.apps.googleusercontent.com',
    iosBundleId: 'com.example.yogaApp',
  );
}
